run_all_in_parallel:
	make -j test_XP_chrome_43 test_OSX10.10_safari_8

test_XP_chrome_43:
	platform=XP browser_name=chrome version=43 lettuce

test_OSX10.10_safari_8:
	platform="OS X 10.10" browser_name=safari version=8 lettuce
